packages:
  - packages/*
  - dev/packages/*
  - apps/*

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - nx
  - sharp
  - unrs-resolver

strictPeerDependencies: false
