import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { Services } from '@ssword-ui/react';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { PropsWithChildren } from 'react';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

function ClientLayout({ children }: PropsWithChildren) {
	'use client';
	return (
		<>
			<Header />
			<main className="flex-1">{children}</main>
			<Footer />
		</>
	);
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Services.Theming.Provider>
					<div className="flex flex-col">
						<ClientLayout>{children}</ClientLayout>
					</div>
				</Services.Theming.Provider>
			</body>
		</html>
	);
}
